### ISSUE TITLE
Error while appending an image file

### ISSUE THREAD

**Issue by EzequielAdrianM** [felixge/node-form-data#105]
socket.on('publication', function (postdata) {
        var form = new FormData();
        form.append('my_field', 'my_value');
        form.append('file', {
            filename: 'photo.jpg',
            ContentType: 'image/jpg',
            knownLength: 18906
        });
    });

This is the error on the console:

    [TypeError: Object #<Object> has no method 'on']

The idea is to send a POST request in the form-data way to another web application including all the multipart data format (the boundary and the image file itself)
Thankyou!

**Comment by alexindigo** [comment]
It's expecting to have file as stream object. https://nodejs.org/api/fs.html#fs_fs_createreadstream_path_options

**Comment by EzequielAdrianM** [comment]
Thankyou, the problem was solved!
