### ISSUE TITLE
Update combined-stream

### ISSUE THREAD

**Issue by dgsunesen** [felixge/node-form-data#111]
See this: https://github.com/request/request/pull/1560#issuecomment-110675511

**Comment by dgsunesen** [comment]
tldr; 
Update "combined-stream" dependency to version ~1.0.1

**Comment by dgsunesen** [comment]
Ping

**Comment by alexindigo** [comment]
hey, sorry for the delay. It's getting there.

https://github.com/felixge/node-form-data/pull/114 and https://www.npmjs.com/package/form-data
