### ISSUE TITLE
Submit multidimensional array

### ISSUE THREAD

**Issue by plamen-paskov-pp** [felixge/node-form-data#116]
Hey,
Sorry if that already exists but i can't submit multidimensional array like this:

var formData = {
    key1: 'key1',
    key2: {
        innerKey1: 'foo',
        innerKey2: 'bar'
    }
};

**Comment by alexindigo** [comment]
I think this thread would shed light on the problem: https://github.com/felixge/node-form-data/issues/92

**Comment by plamen-paskov-pp** [comment]
thanks @alexindigo ! i found the solution there. for php end it is something like

var formData {
    'data[key1]': 'val1',
    'data[key2]': 'val2'
};
