### ISSUE TITLE
Content-Type "false" set when file does not have an extension

### ISSUE THREAD

**Issue by BernhardBln** [felixge/node-form-data#118]
When you send a file with a filename that does not have an extension, the content type of that part is set to "false", which obviously ends in an error when talking to the server.

The problematic part is this line:

```javascript
header +=
        '; filename="' + path.basename(options.filename || value.path) + '"' + FormData.LINE_BREAK +
        'Content-Type: ' +  (options.contentType || mime.lookup(options.filename || value.path));
```

mime.lookup returns false, when it can't determine the content type.

Maybe replace by this?

```javascript
header +=
        '; filename="' + path.basename(options.filename || value.path) + '"' + FormData.LINE_BREAK +
        'Content-Type: ' +  (options.contentType || mime.lookup(options.filename || value.path)
                          || 'application/octet-stream');
```

**Comment by DylanPiercey** [comment]
:+1:

Would certainly be better to default to `application/octet-stream`.
