### ISSUE TITLE
Memory leak when uploading large files using readable stream

### ISSUE THREAD

**Issue by andyhu** [felixge/node-form-data#64]
There is a big memory leak when doing a file upload. When appending a readable stream, it buffers entire content of the readable stream no matter if knownSize is given. I have profiled the app and the leak is from Buffer objects (more than 20, 000 of them, each have a size of 64k!). The file size more than 600M and it takes more than 600M memory, which is a big problem.
Here is the code when I test:

```
var FormData = require('form-data');
var http = require('http');
var fs = require('fs');


var form = new FormData();
var fPath = 'K:\\ubuntu.iso';
var stat = fs.statSync(fPath);

form.append('file', fs.createReadStream(fPath), {knownSize: stat.size});
form.submit('http://127.0.0.1:3000/upload', function(err, res) {
  if (err) throw err;
  console.log('Done');
});
```

I think the leak may caused by the use of deferred-stream. However I can't manage to fix it. Any ideas?

**Comment by cxreg** [comment]
This was fixed in https://github.com/felixge/node-combined-stream/pull/16 correct?  I ran into this issue as well but after upgrading combined-stream it seems to behave correctly now

**Comment by frankrousseau** [comment]
Yes it's fixed!

**Comment by alexindigo** [comment]
Pulled in updated `combined-stream` into `v1.0.0-rc1`, please take a look. Thank you.
