### ISSUE TITLE
Set Custom Headers 

### ISSUE THREAD

**Issue by arb** [felixge/node-form-data#83]
I would like to set the `content-transfer-encoding` header via `form.append`. Is this currently possible short of creating and managing ALL of the custom headers?

**Comment by DylanPiercey** [comment]
You can add to the headers when you retrieve them from form data like so:
```javascript
var form = new FormData();
form.getHeaders({ "content-transfer-encoding": ...});
```

Not sure if this is what you are looking for.

**Comment by arb** [comment]
This was so long ago, I don't even remember what I was doing with this.
